### PR TITLE
Fix for https://github.com/WICG/inert/issues/51

### PR DESCRIPTION
**Pull request by vcorr**
Here is a work around as described in the issue.

### CODE REVIEW

**Comment by vcorr** [comment]
There seems to be an issue with Saucelab config? 
`Your test errored. The Sauce VMs failed to start the browser or device`
8 most recent Travis builds have failed for similar(?) problem

**Comment by robdodson** [comment]
Yeah I'm about ready to toss out our current saucelabs setup :\

**Comment by robdodson** [comment]
OK I fixed the issue with sauce labs. If you want to rebase against master it should work again (fingers crossed).

**Comment by vcorr** [comment]
Yep, that fixed it :)

**Comment by robdodson** [comment]
Fixed by #54

**Pull request closed without merging**
