### PR TITLE
Make the compiled version use ES3 syntax and not ES5 syntax to have it not cause script parsing errors in IE8

### PR DESCRIPTION
**Pull request by JakeChampion**
I'm looking to add this to polyfill.io but noticed it errors during parsing as the code is es5 and not es3

### CODE REVIEW

**Comment by robdodson** [comment]
It looks like the built version of the library is the same file size (26k unminified, 7k minified) so I'm supportive of this.

@alice wdyt?

**Comment by JakeChampion** [comment]
It should be minimal impact because all it does is turn properties and methods which have a name that is also a keyword from being in dot notation to being in bracket notation. E.G. `a.delete(b)` becomes `a['delete'](b)`

**Comment by alice** [comment]
:+1:

**Comment by andrewgadziksonos** [comment]
🙌 Thank you!

**Comment by JakeChampion** [comment]
Thanks the merging this in :-)

Is there a scheduled date for when this will be released in a new version of the npm package at all?

**Comment by robdodson** [comment]
I can do a release today.

**Comment by robdodson** [comment]
just published 2.1.2 which contains this change.

**Pull request merged**
